"""
Multi-agent pipeline using LangGraph.
Orchestrates: Planner → PaperSearch → Summary → Graph → Writer
"""

import logging
import time
from pathlib import Path

from langgraph.graph import StateGraph, END

from agents.state import LitReviewState
from agents.planner import planner_agent
from agents.paper_search import paper_search_agent
from agents.summary import summary_agent
from agents.graph_agent import graph_agent
from agents.writer import writer_agent

logger = logging.getLogger(__name__)


def build_pipeline() -> StateGraph:
    """Build and compile the LangGraph pipeline."""

    workflow = StateGraph(LitReviewState)

    # Add nodes
    workflow.add_node("planner",      planner_agent)
    workflow.add_node("paper_search", paper_search_agent)
    workflow.add_node("summary",      summary_agent)
    workflow.add_node("graph",        graph_agent)
    workflow.add_node("writer",       writer_agent)

    # Define flow
    workflow.set_entry_point("planner")
    workflow.add_edge("planner",      "paper_search")
    workflow.add_edge("paper_search", "summary")
    workflow.add_edge("summary",      "graph")
    workflow.add_edge("graph",        "writer")
    workflow.add_edge("writer",        END)

    return workflow.compile()


def run_literature_review(topic: str) -> dict:
    """
    Run the full multi-agent pipeline for a literature review.

    Args:
        topic: research topic to review

    Returns:
        Final state dict with literature_review, citations, etc.
    """
    print("\n" + "="*70)
    print(f"LITERATURE REVIEW AGENT PIPELINE")
    print(f"Topic: {topic}")
    print("="*70)

    start = time.time()

    # Initialize state
    initial_state: LitReviewState = {
        "topic":               topic,
        "sub_queries":         [],
        "plan_reasoning":      "",
        "retrieved_papers":    [],
        "retrieved_chunks":    [],
        "paper_summaries":     [],
        "graph_relationships": [],
        "timeline":            [],
        "literature_review":   "",
        "citations":           [],
        "total_papers_found":  0,
        "errors":              [],
    }

    pipeline = build_pipeline()

    # Run pipeline
    final_state = pipeline.invoke(initial_state)

    elapsed = int((time.time() - start))

    print(f"\n{'='*70}")
    print(f"PIPELINE COMPLETE — {elapsed}s")
    print(f"  Papers found:     {final_state['total_papers_found']}")
    print(f"  Summaries:        {len(final_state['paper_summaries'])}")
    print(f"  Relationships:    {len(final_state['graph_relationships'])}")
    print(f"  Citations:        {len(final_state['citations'])}")
    print(f"  Errors:           {len(final_state['errors'])}")
    if final_state["errors"]:
        for e in final_state["errors"]:
            print(f"    - {e}")
    print(f"{'='*70}")

    return final_state


def save_literature_review(state: dict, output_dir: str = "docs") -> str:
    """Save the literature review to a markdown file."""
    Path(output_dir).mkdir(exist_ok=True)

    topic_slug = state["topic"].lower().replace(" ", "_")[:40]
    filename = f"{output_dir}/lit_review_{topic_slug}.md"

    with open(filename, "w", encoding="utf-8") as f:
        f.write(f"# Literature Review: {state['topic']}\n\n")
        f.write(f"*Generated by Hybrid KAG Multi-Agent Pipeline*\n\n")
        f.write(f"**Papers reviewed:** {state['total_papers_found']}\n\n")
        f.write("---\n\n")
        f.write(state["literature_review"])
        f.write("\n\n---\n\n")
        f.write("## Search Queries Used\n\n")
        for q in state.get("sub_queries", []):
            f.write(f"- {q}\n")
        f.write("\n## Timeline\n\n")
        for t in state.get("timeline", []):
            f.write(
                f"- **{t['year']}** — {t['title']}"
                f"{(' (' + ', '.join(t['methods'][:2]) + ')') if t['methods'] else ''}\n"
            )

    print(f"\n✓ Saved to {filename}")
    return filename